server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-platform
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # on app start
    show-sql: true # show sql logs in console
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.postgresql.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:sql/createManyTagsProcedure.sql
app:
  security:
    jwt:
      secret-key: 1234561234561234561234561234561234561234561234561234561234561234
      expiration: 86400000 # a day

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE # security filters logs // logging.level.org.springframework.security=TRACE

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
